## To check out all the arithmetic operations 
 [see](https://pytorch.org/docs/stable/torch.html "link here")

In [35]:
# https://docs.microsoft.com/en-us/learn/modules/intro-machine-learning-pytorch/2-tensors

%matplotlib inline

In [5]:
import torch
import numpy as np

### Initializing a Tensor

In [12]:
# from the data

data = [[1, 2],[3, 4]]
type(data)
x_data = torch.tensor(data)
(x_data)

tensor([[1, 2],
        [3, 4]])

In [11]:
# from numpy array

np_array = np.array(data)
np_array
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [25]:
# from another tensor

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2409, 0.2927],
        [0.9519, 0.5774]]) 



In [23]:
# With random or constant values

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5045, 0.8211, 0.8717],
        [0.3420, 0.9049, 0.0538]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
# Tensor attributes
tensor = torch.rand(3,4)
# print(dir(tensor))

In [88]:
torch.cuda.is_available()

False

In [43]:
torch.cuda.is_initialized()

False

In [46]:
torch.__version__
torch.cuda.device_count()

0

In [48]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [50]:
# joining tensors

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [51]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [71]:
# Single-element tensors

agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))


12.0 <class 'float'>


12.0

In [72]:
# not recommended use of in-place operation

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [79]:
# tensor to numpy

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

print("A change in tensor will reflect in numpy.")
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
A change in tensor will reflect in numpy.
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [85]:
np.add(1,n, out=n)
n

array([6., 6., 6., 6., 6.], dtype=float32)

In [87]:
dtype = torch.float
device = torch.device("cpu")
device = torch.device("cuda:0")  # Uncomment this to run on GPU
